<?php

namespace Database\Seeders;

use App\Models\Position;
use Illuminate\Database\Seeder;

class positionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Position::insert([
            ['name' => 'Camat Binawidya'],
            ['name' => 'Lurah Harjosari'],
            ['name' => 'Lurah Padang Bulan'],
            ['name' => 'Lurah Sukamulia'],
            ['name' => 'Camat Bukitraya'],
            ['name' => 'Lurah Industri Tenayan'],
            ['name' => 'Lurah Padang Terubuk'],
            ['name' => 'Lurah Sukaramai'],
            ['name' => 'Camat Kulim'],
            ['name' => 'Lurah Jadirejo'],
            ['name' => 'Lurah Palas'],
            ['name' => 'Lurah Sumahilang'],
            ['name' => 'Camat Limapuluh'],
            ['name' => 'Lurah Kampung Bandar'],
            ['name' => 'Lurah Pebatuan'],
            ['name' => 'Lurah Sungai Sibam'],
            ['name' => 'Camat Marpoyan Damai'],
            ['name' => 'Lurah Kampung Baru'],
            ['name' => 'Lurah Pematang Kapau'],
            ['name' => 'Lurah Sungaiambang'],
            ['name' => 'Camat Payung Sekaki'],
            ['name' => 'Lurah Kampung Dalam'],
            ['name' => 'Lurah Perhentianmarpoyan'],
            ['name' => 'Lurah Sungaiukai'],
            ['name' => 'Camat Pekanbarukota'],
            ['name' => 'Lurah Kampung Melayu'],
            ['name' => 'Lurah Pesisir'],
            ['name' => 'Lurah Tampan'],
            ['name' => 'Camat Rumbai'],
            ['name' => 'Lurah Kampung Tengah'],
            ['name' => 'Lurah Pulau Karomah'],
            ['name' => 'Lurah Tanah Datar'],
            ['name' => 'Camat Rumbai Barat'],
            ['name' => 'Lurah Kedungsari'],
            ['name' => 'Lurah Rantau Panjang'],
            ['name' => 'Lurah Tangkerang Barat'],
            ['name' => 'Camat Rumbai Timur'],
            ['name' => 'Lurah Kota Baru'],
            ['name' => 'Lurah Rejosari'],
            ['name' => 'Lurah Tangkerang Labuai'],
            ['name' => 'Camat Sail'],
            ['name' => 'Lurah Kota Tinggi'],
            ['name' => 'Lurah Rintis'],
            ['name' => 'Lurah Tangkerang Selatan'],
            ['name' => 'Camat Senapelan'],
            ['name' => 'Lurah Kulim'],
            ['name' => 'Lurah Rumbai Bukit'],
            ['name' => 'Lurah Tangkerang Tengah'],
            ['name' => 'Camat Sukajadi'],
            ['name' => 'Lurah LabuhBaru Barat'],
            ['name' => 'Lurah Sago'],
            ['name' => 'Lurah Tangkerang Timur'],
            ['name' => 'Camat Tenayan Raya'],
            ['name' => 'Lurah LabuhBaru Timur'],
            ['name' => 'Lurah Sekip'],
            ['name' => 'Lurah Tangkerang Utara'],
            ['name' => 'Camat Tuah Madani'],
            ['name' => 'Lurah Lembah Damai'],
            ['name' => 'Lurah Sialang Rampai'],
            ['name' => 'Lurah Tanjung Rhu'],
            ['name' => 'Lurah Agrowisata'],
            ['name' => 'Lurah Lembah Sari'],
            ['name' => 'Lurah Sialang Sakti'],
            ['name' => 'Lurah Tebing Tinggi Okura'],
            ['name' => 'Lurah Air Dingin'],
            ['name' => 'Lurah Limbungan'],
            ['name' => 'Lurah Sialangmunggu'],
            ['name' => 'Lurah Tirtasiak'],
            ['name' => 'Lurah Air Hitam'],
            ['name' => 'Lurah Limbungan Baru'],
            ['name' => 'Lurah Sidomulyo Barat'],
            ['name' => 'Lurah Tobekgodang'],
            ['name' => 'Lurah Airputih'],
            ['name' => 'Lurah Maharani'],
            ['name' => 'Lurah Sidomulyo Timur'],
            ['name' => 'Lurah Tuah Karya'],
            ['name' => 'Lurah Bambu Kuning'],
            ['name' => 'Lurah Maharatu'],
            ['name' => 'Lurah Simpang Baru'],
            ['name' => 'Lurah Tuah Negeri'],
            ['name' => 'Lurah Bandar Raya'],
            ['name' => 'Lurah Melebung'],
            ['name' => 'Lurah Simpang Empat'],
            ['name' => 'Lurah Tuahmadani'],
            ['name' => 'Lurah Bencah Lesung'],
            ['name' => 'Lurah Mentangor'],
            ['name' => 'Lurah Simpang Tiga'],
            ['name' => 'Lurah Umban Sari'],
            ['name' => 'Lurah Binawidya'],
            ['name' => 'Lurah Meranti Pandak'],
            ['name' => 'Lurah Sri Meranti'],
            ['name' => 'Lurah Wonorejo'],
            ['name' => 'Lurah Cintaraja'],
            ['name' => 'Lurah Muara Fajar Barat'],
            ['name' => 'Lurah Sukajadi'],
            ['name' => 'Lurah Delima'],
            ['name' => 'Lurah Muara Fajar Timur'],
            ['name' => 'Lurah Sukamaju'],
            ['name' => 'Sekretaris Daerah'],
        ]);
    }
}
