<?php

namespace Database\Seeders;

use App\Models\Sign;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

class signSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Sign::insert([
            [
                'nip' => '198611202007011001',
                'fullname' => 'ABDUL BARRI, S.IP',
                'classGroupID' => 12,
                'positionID' => 57,
                'positionType' => 'camat',
                'nohp' => '082284012005',
                'email' => 'abdulbarri.tuahmadani@pekanbaru.go.id',
                'nik' => '1471012011860001',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'nip' => '197403312009011002',
                'fullname' => 'H. EDI SUSANTO, SH',
                'classGroupID' => 12,
                'positionID' => 71,
                'positionType' => 'lurah',
                'nohp' => '085263687329',
                'email' => 'edisusanto.tuahmadani@pekanbaru.go.id',
                'nik' => '1401013103740002',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'nip' => '197909192003122001',
                'fullname' => 'FITRIYATI, SP',
                'classGroupID' => 11,
                'positionID' => 67,
                'positionType' => 'lurah',
                'nohp' => '081266399540',
                'email' => 'fitriyati.tuahmadani@pekanbaru.go.id',
                'nik' => '147112590979002',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'nip' => '197010021991031003',
                'fullname' => 'EDY AZWAR, SE',
                'classGroupID' => 12,
                'positionID' => 76,
                'positionType' => 'lurah',
                'nohp' => '08127621104',
                'email' => 'edyazwar.tuahmadani@pekanbaru.go.id',
                'nik' => '1471120210700021',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'nip' => '197807212011021001',
                'fullname' => 'RUSMANTO, S.Sos',
                'classGroupID' => 11,
                'positionID' => 57,
                'positionType' => 'lurah',
                'nohp' => '081275460210',
                'email' => 'rusmanto.tuahmadani@pekanbaru.go.id',
                'nik' => '1401022107788002',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'nip' => '196412311985031052',
                'fullname' => 'AGUS SUTIARTONO',
                'classGroupID' => 12,
                'positionID' => 73,
                'positionType' => 'lurah',
                'nohp' => '081266761944',
                'email' => 'agussutiartono.tuahmadani@pekanbaru.go.id',
                'nik' => '1471083112640041',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'nip' => '197511092007011002',
                'fullname' => 'EDI SUHERMAN, S.Sos., M.Si',
                'classGroupID' => 12,
                'positionID' => 1,
                'positionType' => 'camat',
                'nohp' => '082389099900',
                'email' => 'edisuherman.binawidya@pekanbaru.go.id',
                'nik' => '1401010911750002',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'nip' => '197410102007011011',
                'fullname' => 'ZAKRIS, S.Pi., S.IP',
                'classGroupID' => 10,
                'positionID' => 79,
                'positionType' => 'lurah',
                'nohp' => '081268791097',
                'email' => 'zakris.binawidya@pekanbaru.go.id',
                'nik' => '1471121010740041',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'nip' => '199301142015071004',
                'fullname' => 'MUHAMMAD RIZKIADY RAMBE, S.STP',
                'classGroupID' => 10,
                'positionID' => 96,
                'positionType' => 'lurah',
                'nohp' => '085277765669',
                'email' => 'mrizkiadyrambe.binawidya@pekanbaru.go.id',
                'nik' => '1210021401930002',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'nip' => '197601012006051003',
                'fullname' => 'H. YASIR ARAFAT, S.Sos',
                'classGroupID' => 11,
                'positionID' => 72,
                'positionType' => 'lurah',
                'nohp' => '081378122599',
                'email' => 'yasirarafat.binawidya@pekanbaru.go.id',
                'nik' => '1401010101760002',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'nip' => '197205131997031001',
                'fullname' => 'SYAMSURIZAL, SE',
                'classGroupID' => 12,
                'positionID' => 89,
                'positionType' => 'lurah',
                'nohp' => '082173325190',
                'email' => 'syamsurizal.binawidya@pekanbaru.go.id',
                'nik' => '1471081305720042',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'nip' => '197212311997011001',
                'fullname' => 'SARNUBI, M.Si',
                'classGroupID' => 12,
                'positionID' => 16,
                'positionType' => 'lurah',
                'nohp' => '082384919551',
                'email' => 'sarnubi.binawidya@pekanbaru.go.id',
                'nik' => '1404090201700001',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'nip' => '198002021999121001',
                'fullname' => 'FAUZAN, S.STP., M.Si',
                'classGroupID' => 13,
                'positionID' => 21,
                'positionType' => 'camat',
                'nohp' => '082169556630',
                'email' => 'fauzan.payungsekaki@pekanbaru.go.id',
                'nik' => '1471120202800042',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'nip' => '196805141993091001',
                'fullname' => 'ZULFI IJUM, S.Kom., M.Si',
                'classGroupID' => 13,
                'positionID' => 69,
                'positionType' => 'lurah',
                'nohp' => '08127571970',
                'email' => 'zulfiijum.payungsekaki@pekanbaru.go.id',
                'nik' => '1471111405680001',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'nip' => '196407081987031004',
                'fullname' => 'HERMAN, S.Sos',
                'classGroupID' => 12,
                'positionID' => 81,
                'positionType' => 'lurah',
                'nohp' => '082385305882',
                'email' => 'herman.payungsekaki@pekanbaru.go.id',
                'nik' => '1471070807640001',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'nip' => '198511152010011012',
                'fullname' => 'WAHYU NOFIYANDRI, M.Pd',
                'classGroupID' => 11,
                'positionID' => 50,
                'positionType' => 'lurah',
                'nohp' => '081275011662',
                'email' => 'wahyunofiyandri.payungsekaki@pekanbaru.go.id',
                'nik' => '1471121511850002',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'nip' => '197804212010011009',
                'fullname' => 'ZULKIFLI, S.HI',
                'classGroupID' => 11,
                'positionID' => 54,
                'positionType' => 'lurah',
                'nohp' => '081365421997',
                'email' => 'zulkifli.payungsekaki@pekanbaru.go.id',
                'nik' => '1471012104780001',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'nip' => '198311072011022001',
                'fullname' => 'SUCI TRIANINGSIH, SH',
                'classGroupID' => 12,
                'positionID' => 68,
                'positionType' => 'lurah',
                'nohp' => '082174700899',
                'email' => 'sucitrianingsih.payungsekaki@pekanbaru.go.id',
                'nik' => '1471074711830002',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'nip' => '197008021995122001',
                'fullname' => 'HERMAYENI, S.Pd',
                'classGroupID' => 14,
                'positionID' => 28,
                'positionType' => 'lurah',
                'nohp' => '081371133670',
                'email' => 'hermayeni.payungsekaki@pekanbaru.go.id',
                'nik' => '1471014208700001',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'nip' => '196701041990031015',
                'fullname' => 'MARZALI, S.Sos',
                'classGroupID' => 13,
                'positionID' => 9,
                'positionType' => 'camat',
                'nohp' => '081365281994',
                'email' => 'marzali.kulim@pekanbaru.go.id',
                'nik' => '1401020401610000',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'nip' => '198008062010012008',
                'fullname' => 'AGUSTINA, S.KM',
                'classGroupID' => 10,
                'positionID' => 46,
                'positionType' => 'lurah',
                'nohp' => '085375281980',
                'email' => 'agustina.kulim@pekanbaru.go.id',
                'nik' => '1471104608800103',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'nip' => '197511192001122003',
                'fullname' => 'BISMIHAYATI, SH',
                'classGroupID' => 12,
                'positionID' => 86,
                'positionType' => 'lurah',
                'nohp' => '081365622265',
                'email' => 'bismihayati.kulim@pekanbaru.go.id',
                'nik' => '1471105911750001',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'nip' => '197002282007011005',
                'fullname' => 'MOHAMMAD SETYA CHANDRA WIJAYA, SH',
                'classGroupID' => 12,
                'positionID' => 15,
                'positionType' => 'lurah',
                'nohp' => '081367788826',
                'email' => 'msetyachandra.tenayanraya@pekanbaru.go.id',
                'nik' => '1471032802700021',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'nip' => '196510101992031001',
                'fullname' => 'H. TAR AJAMAN, S.Sos',
                'classGroupID' => 12,
                'positionID' => 19,
                'positionType' => 'lurah',
                'nohp' => '08127602476',
                'email' => 'tarajaman.kulim@pekanbaru.go.id',
                'nik' => '1471101010650043',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'nip' => '197810012007011005',
                'fullname' => 'IRIYANTO, S.HI',
                'classGroupID' => 10,
                'positionID' => 59,
                'positionType' => 'lurah',
                'nohp' => '081365733213',
                'email' => 'irianto.kulim@pekanbaru.go.id',
                'nik' => '1471010110780001',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'nip' => '198308032001122002',
                'fullname' => 'INDAH VIDYA ASTUTI, S.STP',
                'classGroupID' => 13,
                'positionID' => 53,
                'positionType' => 'camat',
                'nohp' => '081374335138',
                'email' => 'indahvidyaastuti.tenayanraya@pekanbaru.go.id',
                'nik' => '1471074308830101',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'nip' => '197106151994031010',
                'fullname' => 'H. HASAN NUSI, SE',
                'classGroupID' => 12,
                'positionID' => 63,
                'positionType' => 'lurah',
                'nohp' => '08127689615',
                'email' => 'hasannusi.tenayanraya@pekanbaru.go.id',
                'nik' => '1471031506710001',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'nip' => '199308302015071002',
                'fullname' => 'RIZNALDI ANANTA PRATAMA, S.STP',
                'classGroupID' => 10,
                'positionID' => 77,
                'positionType' => 'lurah',
                'nohp' => '081266950194',
                'email' => 'riznaldiananta.tenayanraya@pekanbaru.go.id',
                'nik' => '1471073008930021',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'nip' => '199109282014061001',
                'fullname' => 'ALWIS SEPTIAN, S.STP',
                'classGroupID' => 10,
                'positionID' => 6,
                'positionType' => 'lurah',
                'nohp' => '082284563136',
                'email' => 'alwisseptian.kulim@pekanbaru.go.id',
                'nik' => '1401012809910004',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'nip' => '199011192015071001',
                'fullname' => 'REZA DEWANTARA, S.STP',
                'classGroupID' => 10,
                'positionID' => 82,
                'positionType' => 'lurah',
                'nohp' => '082170066592',
                'email' => 'rezadewantara.tenayanraya@pekanbaru.go.id',
                'nik' => '1471101911900021',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'nip' => '199301052015071003',
                'fullname' => 'ARRASYID KELANA PUTERA, S.STP., MM',
                'classGroupID' => 10,
                'positionID' => 39,
                'positionType' => 'lurah',
                'nohp' => '08117573553',
                'email' => 'arrasyidkelana.tenayanraya@pekanbaru.go.id',
                'nik' => '1471040501930061',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'nip' => '197412192009011004',
                'fullname' => 'SUWANDI NASUTION, S.IP',
                'classGroupID' => 10,
                'positionID' => 85,
                'positionType' => 'lurah',
                'nohp' => '082382855251',
                'email' => 'suwandinasution.tenayanraya@pekanbaru.go.id',
                'nik' => '1471091912740041',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'nip' => '198301192008011007',
                'fullname' => 'BENI WAHYUDY, SP',
                'classGroupID' => 10,
                'positionID' => 52,
                'positionType' => 'lurah',
                'nohp' => '08127619745',
                'email' => 'beniwahyudy.tenayanraya@pekanbaru.go.id',
                'nik' => '1471041901830001',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'nip' => '196611261990031005',
                'fullname' => 'SYARIFUDIN, SH',
                'classGroupID' => 12,
                'positionID' => 80,
                'positionType' => 'lurah',
                'nohp' => '08127611735',
                'email' => 'syarifudin.tenayanraya@pekanbaru.go.id',
                'nik' => '1471102611660001',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'nip' => '197212282000031004',
                'fullname' => 'SYAMSUDIN, S.Sos',
                'classGroupID' => 12,
                'positionID' => 37,
                'positionType' => 'camat',
                'nohp' => '082387911038',
                'email' => 'syamsudin.rumbaitimur@pekanbaru.go.id',
                'nik' => '1471062812720001',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'nip' => '196404162001121003',
                'fullname' => 'BURHAN, S.Sos',
                'classGroupID' => 12,
                'positionID' => 64,
                'positionType' => 'lurah',
                'nohp' => '085274830211',
                'email' => 'burhan.rumbaitimur@pekanbaru.go.id',
                'nik' => '1471121604640021',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'nip' => '197904221998031003',
                'fullname' => 'R. MERZA VENRIAN, S.Sos',
                'classGroupID' => 12,
                'positionID' => 24,
                'positionType' => 'lurah',
                'nohp' => '081277510198',
                'email' => 'rmerzavenrian.rumbaitimur@pekanbaru.go.id',
                'nik' => '1471076305790001',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'nip' => '199206272014061001',
                'fullname' => 'SANTRI IMAM, S.STP',
                'classGroupID' => 10,
                'positionID' => 20,
                'positionType' => 'lurah',
                'nohp' => '08117680027',
                'email' => 'santriimam.rumbaitimur@pekanbaru.go.id',
                'nik' => '1471062706920001',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'nip' => '199307022015071001',
                'fullname' => 'IIF SYAEFULLAH JB, S.STP',
                'classGroupID' => 10,
                'positionID' => 62,
                'positionType' => 'lurah',
                'nohp' => '082174715709',
                'email' => 'iifsyaefullah.rumbaitimur@pekanbaru.go.id',
                'nik' => '1407030207930001',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'nip' => '198406112008012007',
                'fullname' => 'WELFINASARI HARAHAP, S.Sos',
                'classGroupID' => 10,
                'positionID' => 66,
                'positionType' => 'lurah',
                'nohp' => '085263697522',
                'email' => 'welfinasariharahap.rumbaitimur@pekanbaru.go.id',
                'nik' => '1471065106840021',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'nip' => '197001021996061001',
                'fullname' => 'MUHAMMAD SALIM, S.Pd., M.IP',
                'classGroupID' => 13,
                'positionID' => 58,
                'positionType' => 'lurah',
                'nohp' => '082174816655',
                'email' => 'muhammadsalim.rumbai@pekanbaru.go.id',
                'nik' => '1471090201700061',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'nip' => '196907211993032002',
                'fullname' => 'DASRIATI, S.Sos',
                'classGroupID' => 12,
                'positionID' => 70,
                'positionType' => 'lurah',
                'nohp' => '085376888669',
                'email' => 'dasriati.rumbai@pekanbaru.go.id',
                'nik' => '1471126107690001',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'nip' => '197005222001121003',
                'fullname' => 'SILVENUS HENDRA, SH',
                'classGroupID' => 11,
                'positionID' => 90,
                'positionType' => 'lurah',
                'nohp' => '082381066516',
                'email' => 'silvenushendra.rumbai@pekanbaru.go.id',
                'nik' => '1471122205720001',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'nip' => '199309072015071004',
                'fullname' => 'WENDI YULIASDI, S.STP',
                'classGroupID' => 11,
                'positionID' => 91,
                'positionType' => 'lurah',
                'nohp' => '081220551143',
                'email' => 'wendiyuliasdi.rumbai@pekanbaru.go.id',
                'nik' => '1471070709930001',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'nip' => '199103042012061001',
                'fullname' => 'M. RIZKY PRAMDANI, S.STP',
                'classGroupID' => 11,
                'positionID' => 11,
                'positionType' => 'lurah',
                'nohp' => '082126663630',
                'email' => 'mrizkypramdani.rumbai@pekanbaru.go.id',
                'nik' => '1471080503910001',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'nip' => '196805012001122004',
                'fullname' => 'Hj. ASPARIDA, S.Sos',
                'classGroupID' => 12,
                'positionID' => 88,
                'positionType' => 'lurah',
                'nohp' => '081371716729',
                'email' => 'asparida.rumbai@pekanbaru.go.id',
                'nik' => '1471064105680001',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'nip' => '198210172001122001',
                'fullname' => 'VEMI HERLIZA, S.STP',
                'classGroupID' => 13,
                'positionID' => 33,
                'positionType' => 'camat',
                'nohp' => '081264999000',
                'email' => 'vemiherliza.rumbaibarat@pekanbaru.go.id',
                'nik' => '1471125710820021',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'nip' => '197310011997031005',
                'fullname' => 'MUCHLIS, S.KM., M.Si',
                'classGroupID' => 12,
                'positionID' => 97,
                'positionType' => 'lurah',
                'nohp' => '082283838389',
                'email' => 'muchlis.rumbaibarat@pekanbaru.go.id',
                'nik' => '1471020110730001',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'nip' => '196501021995031002',
                'fullname' => 'MAHDAWI, S.Sos',
                'classGroupID' => 12,
                'positionID' => 94,
                'positionType' => 'lurah',
                'nohp' => '085376964879',
                'email' => 'mahdawi.rumbaibarat@pekanbaru.go.id',
                'nik' => '1471080201650021',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'nip' => '198912282012061003',
                'fullname' => 'NANDA EDDYAN HARSONO, S.STP',
                'classGroupID' => 10,
                'positionID' => 47,
                'positionType' => 'lurah',
                'nohp' => '085321352334',
                'email' => 'nandaeddyan.rumbaibarat@pekanbaru.go.id',
                'nik' => '1471042812890001',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'nip' => '198912082010101002',
                'fullname' => 'DELAWIJA ANDRIO, S.IP',
                'classGroupID' => 10,
                'positionID' => 35,
                'positionType' => 'lurah',
                'nohp' => '085220067708',
                'email' => 'delawijaandrio.rumbaibarat@pekanbaru.go.id',
                'nik' => '1471100812890061',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'nip' => '198108022007011004',
                'fullname' => 'ZULKIFLI, S.Sos',
                'classGroupID' => 10,
                'positionID' => 74,
                'positionType' => 'lurah',
                'nohp' => '081275099991',
                'email' => 'zulkifli.rumbaibarat@pekanbaru.go.id',
                'nik' => '1471030208810001',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'nip' => '198212272010011027',
                'fullname' => 'SARDEF SAPUTRA, SP',
                'classGroupID' => 11,
                'positionID' => 61,
                'positionType' => 'lurah',
                'nohp' => '08117699188',
                'email' => 'sardefsaputra.rumbaibarat@pekanbaru.go.id',
                'nik' => '1471052712820001',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'nip' => '197206281992031001',
                'fullname' => 'JUNAEDY, S.Sos., M.Si',
                'classGroupID' => 14,
                'positionID' => 17,
                'positionType' => 'camat',
                'nohp' => '085271837761',
                'email' => 'junaedy.marpoyandamai@pekanbaru.go.id',
                'nik' => '1471082806720001',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'nip' => '198301072009021001',
                'fullname' => 'RIZKI AMELIA, S.Sos., M.IP',
                'classGroupID' => 11,
                'positionID' => 48,
                'positionType' => 'lurah',
                'nohp' => '085278777979',
                'email' => 'rizkiamelia.marpoyandamai@pekanbaru.go.id',
                'nik' => '1471090701830081',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'nip' => '197110071995041001',
                'fullname' => 'EDI WARDILA, S.Pd., M.Pd',
                'classGroupID' => 13,
                'positionID' => 36,
                'positionType' => 'lurah',
                'nohp' => '081219389794',
                'email' => 'ediwardila.marpoyandamai@pekanbaru.go.id',
                'nik' => '1471090710710001',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'nip' => '199111082012061001',
                'fullname' => 'JOKO ARIF SANTOSO, S.STP',
                'classGroupID' => 10,
                'positionID' => 78,
                'positionType' => 'lurah',
                'nohp' => '081299333408',
                'email' => 'jokoarifsantoso.marpoyandamai@pekanbaru.go.id',
                'nik' => '1208080811910002',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'nip' => '198802092007011001',
                'fullname' => 'EDWAR BRATA PUTRA, S.IP',
                'classGroupID' => 12,
                'positionID' => 75,
                'positionType' => 'lurah',
                'nohp' => '082383284378',
                'email' => 'edwarbrata.marpoyandamai@pekanbaru.go.id',
                'nik' => '1308050902880001',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'nip' => '196710171995031002',
                'fullname' => 'SAID AHMAD ZAMZAMI, SE',
                'classGroupID' => 12,
                'positionID' => 92,
                'positionType' => 'lurah',
                'nohp' => '081268658061',
                'email' => 'saidahmadzamzami.marpoyandamai@pekanbaru.go.id',
                'nik' => '1471041710670001',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'nip' => '196610061986081001',
                'fullname' => 'ELDA SUHANURA',
                'classGroupID' => 11,
                'positionID' => 23,
                'positionType' => 'lurah',
                'nohp' => '082173350910',
                'email' => 'eldasuhanura.marpoyandamai@pekanbaru.go.id',
                'nik' => '1471070610660041',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'nip' => '197203051993081002',
                'fullname' => 'FACHRUDDIN PANGGABEAN, S.Sos., M.AP',
                'classGroupID' => 13,
                'positionID' => 41,
                'positionType' => 'camat',
                'nohp' => '0811760400',
                'email' => 'fachruddinpanggabean.sail@pekanbaru.go.id',
                'nik' => '1471050503720001',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'nip' => '198511162010012030',
                'fullname' => 'MEDIA NOVA, S.Sos., M.Si',
                'classGroupID' => 11,
                'positionID' => 93,
                'positionType' => 'lurah',
                'nohp' => '08117583100',
                'email' => 'medianova.sail@pekanbaru.go.id',
                'nik' => '1408015611850001',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'nip' => '199112292016091001',
                'fullname' => 'MUHAMMAD ICHFAN, S.STP',
                'classGroupID' => 10,
                'positionID' => 98,
                'positionType' => 'lurah',
                'nohp' => '082219152522',
                'email' => 'muhammadichfan.sail@pekanbaru.go.id',
                'nik' => '1471102912910001',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'nip' => '199306062015072001',
                'fullname' => 'R. FARDHANIA ISYAURA, S.STP',
                'classGroupID' => 10,
                'positionID' => 4,
                'positionType' => 'lurah',
                'nohp' => '08117761993',
                'email' => 'rfardhaniaisyaura.sail@pekanbaru.go.id',
                'nik' => '2172044606930002',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'nip' => '197403201994031002',
                'fullname' => 'FABILLAH SANDY, SE., M.AP',
                'classGroupID' => 13,
                'positionID' => 45,
                'positionType' => 'camat',
                'nohp' => '081363889899',
                'email' => 'fabillahsandy.senapelan@pekanbaru.go.id',
                'nik' => '1471052003740002',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'nip' => '196310271986031006',
                'fullname' => 'ZULFAHMI',
                'classGroupID' => 8,
                'positionID' => 3,
                'positionType' => 'lurah',
                'nohp' => '081266310144',
                'email' => 'zulfahmi.senapelan@pekanbaru.go.id',
                'nik' => '1471052710630001',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'nip' => '196908072005021001',
                'fullname' => 'SYAFRIANTO, S.Pd',
                'classGroupID' => 12,
                'positionID' => 7,
                'positionType' => 'lurah',
                'nohp' => '08127526498',
                'email' => 'syafrianto.senapelan@pekanbaru.go.id',
                'nik' => '1471080708690001',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'nip' => '199307112015071003',
                'fullname' => 'ANDY ABDILLAH, S.STP',
                'classGroupID' => 10,
                'positionID' => 51,
                'positionType' => 'lurah',
                'nohp' => '082285061370',
                'email' => 'andyabdillah.senapelan@pekanbaru.go.id',
                'nik' => '1471091107930001',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'nip' => '196310101985011002',
                'fullname' => 'T. JUNAIDI',
                'classGroupID' => 12,
                'positionID' => 22,
                'positionType' => 'lurah',
                'nohp' => '08127601008',
                'email' => 'tjunaidi.senapelan@pekanbaru.go.id',
                'nik' => '1471011010630021',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'nip' => '198408182010012005',
                'fullname' => 'META SATRIA, S.Mn',
                'classGroupID' => 10,
                'positionID' => 14,
                'positionType' => 'lurah',
                'nohp' => '081275875745',
                'email' => 'metasatria.senapelan@pekanbaru.go.id',
                'nik' => '1307045808840003',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'nip' => '197101061992032003',
                'fullname' => 'YENI ERITA. S.Sos',
                'classGroupID' => 12,
                'positionID' => 18,
                'positionType' => 'lurah',
                'nohp' => '081268184775',
                'email' => 'yenierita.senapelan@pekanbaru.go.id',
                'nik' => '1471094601710022',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'nip' => '198204202001121002',
                'fullname' => 'NURHASMINSYAH, S.STP., M.Si',
                'classGroupID' => 13,
                'positionID' => 25,
                'positionType' => 'camat',
                'nohp' => '08126853085',
                'email' => 'nurhasminsyah.pekanbarukota@pekanbaru.go.id',
                'nik' => '1471092004820021',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'nip' => '199311052016091001',
                'fullname' => 'ILHAM NOVLINDO, S.STP',
                'classGroupID' => 10,
                'positionID' => 83,
                'positionType' => 'lurah',
                'nohp' => '085265906166',
                'email' => 'ilhamnovlindo.pekanbarukota@pekanbaru.go.id',
                'nik' => '1471110511930081',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'nip' => '199403012015072001',
                'fullname' => 'NURSYAM RAMADHANI, S.STP',
                'classGroupID' => 10,
                'positionID' => 12,
                'positionType' => 'lurah',
                'nohp' => '081364406553',
                'email' => 'nursyamramadhani.pekanbarukota@pekanbaru.go.id',
                'nik' => '1471074103940022',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'nip' => '199204042015071002',
                'fullname' => 'FAHDIL RAHMAT, S.IP',
                'classGroupID' => 10,
                'positionID' => 32,
                'positionType' => 'lurah',
                'nohp' => '085363805512',
                'email' => 'fahdilrahmat.pekanbarukota@pekanbaru.go.id',
                'nik' => '1471090404920002',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'nip' => '199306112015071004',
                'fullname' => 'EDO BAGUS JUNIANANTA, S.STP',
                'classGroupID' => 10,
                'positionID' => 38,
                'positionType' => 'lurah',
                'nohp' => '081258360300',
                'email' => 'edobagus.pekanbarukota@pekanbaru.go.id',
                'nik' => '6171051106930004',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'nip' => '196409041986031005',
                'fullname' => 'A. MURTI',
                'classGroupID' => 12,
                'positionID' => 8,
                'positionType' => 'lurah',
                'nohp' => '081275758642',
                'email' => 'amurti.pekanbarukota@pekanbaru.go.id',
                'nik' => '1471070409640041',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'nip' => '196502021986031009',
                'fullname' => 'ADEVISAR, SH',
                'classGroupID' => 12,
                'positionID' => 42,
                'positionType' => 'lurah',
                'nohp' => '081365644000',
                'email' => 'adevisar.pekanbarukota@pekanbaru.go.id',
                'nik' => '1471070202650021',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'nip' => '198505022003121001',
                'fullname' => 'INDRA MAULANA MASADI, S.STP., M.Si',
                'classGroupID' => 12,
                'positionID' => 13,
                'positionType' => 'camat',
                'nohp' => '08127532671',
                'email' => 'indramaulana.limapuluh@pekanbaru.go.id',
                'nik' => '1471030205850001',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'nip' => '198307182005012002',
                'fullname' => 'NURHAIDA RITONGA, SE',
                'classGroupID' => 12,
                'positionID' => 43,
                'positionType' => 'lurah',
                'nohp' => '08127694542',
                'email' => 'nurhaidiritonga.limapuluh@pekanbaru.go.id',
                'nik' => '1471095807830021',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'nip' => '199209212015071002',
                'fullname' => 'MUHAMMAD ARIF SURYA DWI PUTRA, S.STP., M.IP',
                'classGroupID' => 11,
                'positionID' => 55,
                'positionType' => 'lurah',
                'nohp' => '082126033744',
                'email' => 'marifsurya.limapuluh@pekanbaru.go.id',
                'nik' => '1407022109920004',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'nip' => '196803121992031011',
                'fullname' => 'ZUBIR YAHYA, S.Pd',
                'classGroupID' => 13,
                'positionID' => 27,
                'positionType' => 'lurah',
                'nohp' => '085272479925',
                'email' => 'zubiryahya.limapuluh@pekanbaru.go.id',
                'nik' => '2101071203680001',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'nip' => '197310111994122001',
                'fullname' => 'Dra. RAHMA NINGSIH, M.Si',
                'classGroupID' => 14,
                'positionID' => 49,
                'positionType' => 'camat',
                'nohp' => '081268791973',
                'email' => 'rahmaningsih.sukajadi@pekanbaru.go.id',
                'nik' => '1471035110730001',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'nip' => '196404221992102001',
                'fullname' => 'EFRI BUDIANTI, S.Sos',
                'classGroupID' => 12,
                'positionID' => 10,
                'positionType' => 'lurah',
                'nohp' => '085272973101',
                'email' => 'efribudianti.sukajadi@pekanbaru.go.id',
                'nik' => '1471076204640041',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'nip' => '197110142003121002',
                'fullname' => 'SAMSAHID, S.Sos',
                'classGroupID' => 12,
                'positionID' => 30,
                'positionType' => 'lurah',
                'nohp' => '082381519999',
                'email' => 'samsahid.sukajadi@pekanbaru.go.id',
                'nik' => '1471081401710001',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'nip' => '197406202010011012',
                'fullname' => 'DARWINDRA, S.Pi',
                'classGroupID' => 11,
                'positionID' => 26,
                'positionType' => 'lurah',
                'nohp' => '085363749888',
                'email' => 'darwindra.sukajadi@pekanbaru.go.id',
                'nik' => '1471092006740001',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'nip' => '196511231990112001',
                'fullname' => 'ZAINIDAR ELVINA, SE',
                'classGroupID' => 12,
                'positionID' => 34,
                'positionType' => 'lurah',
                'nohp' => '081365691123',
                'email' => 'zainidarelfina.sukajadi@pekanbaru.go.id',
                'nik' => '1471026311650001',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'nip' => '199111292014062001',
                'fullname' => 'CICI ELFINO NISTRI, S.STP., M.IP',
                'classGroupID' => 10,
                'positionID' => 2,
                'positionType' => 'lurah',
                'nohp' => '085278224244',
                'email' => 'cicielfino.sukajadi@pekanbaru.go.id',
                'nik' => '1401046911910002',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'nip' => '196706271989081002',
                'fullname' => 'AKHYAR JUNAIDI',
                'classGroupID' => 12,
                'positionID' => 95,
                'positionType' => 'lurah',
                'nohp' => '081371508999',
                'email' => 'akhyarjunaidi.sukajadi@pekanbaru.go.id',
                'nik' => '1471072706670061',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'nip' => '199212222015071001',
                'fullname' => 'RYAN WIBOWO, S.STP',
                'classGroupID' => 10,
                'positionID' => 31,
                'positionType' => 'lurah',
                'nohp' => '081266591834',
                'email' => 'ryanwibowo.sukajadi@pekanbaru.go.id',
                'nik' => '1471102212920041',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'nip' => '199112152014061001',
                'fullname' => 'T. ARDI DWISASTI, S.STP., M.Si',
                'classGroupID' => 12,
                'positionID' => 5,
                'positionType' => 'camat',
                'nohp' => '08117598666',
                'email' => 'tardidwisasti.bukitraya@pekanbaru.go.id',
                'nik' => '1471011512910001',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'nip' => '196507181988101001',
                'fullname' => 'MUHAMMAD NASIR',
                'classGroupID' => 12,
                'positionID' => 87,
                'positionType' => 'lurah',
                'nohp' => '081261950242',
                'email' => 'muhammadnasir.bukitraya@pekanbaru.go.id',
                'nik' => '1471071807650001',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'nip' => '197206062005011006',
                'fullname' => 'YUSIRWAN, SP',
                'classGroupID' => 12,
                'positionID' => 44,
                'positionType' => 'lurah',
                'nohp' => '081371444472',
                'email' => 'yusirwan.bukitraya@pekanbaru.go.id',
                'nik' => '1471100606720001',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'nip' => '198208312010011012',
                'fullname' => 'ZULKEN, SP',
                'classGroupID' => 11,
                'positionID' => 56,
                'positionType' => 'lurah',
                'nohp' => '081378410005',
                'email' => 'zulken.bukitraya@pekanbaru.go.id',
                'nik' => '1401203108820002',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'nip' => '197011022001121001',
                'fullname' => 'KADWADI, S.Sos',
                'classGroupID' => 10,
                'positionID' => 40,
                'positionType' => 'lurah',
                'nohp' => '085363047374',
                'email' => 'kadwadi.bukitraya@pekanbaru.go.id',
                'nik' => '1471100211700001',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'nip' => '199112292014061001',
                'fullname' => 'MUHAMMAD ISMAIL, S.STP., M.Si',
                'classGroupID' => 11,
                'positionID' => 65,
                'positionType' => 'lurah',
                'nohp' => '081267707136',
                'email' => 'muhammadismail.bukitraya@pekanbaru.go.id',
                'nik' => '1471072912910022',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ]

        ]);
    }
}
